# Generated by Django 5.2.2 on 2026-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_uz', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_it', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_es', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_ja', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('seo_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_uz', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_it', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_es', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_ja', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Display order')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_it', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_es', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ja', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('package_type', models.CharField(choices=[('conference', 'Conference'), ('incentive', 'Incentive Trip'), ('exhibition', 'Exhibition'), ('team_building', 'Team Building'), ('retreat', 'Corporate Retreat'), ('product_launch', 'Product Launch')], default='conference', max_length=20, verbose_name='Package type')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='mice/covers/', verbose_name='Cover image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_it', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ja', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('includes', models.TextField(blank=True, verbose_name='Package includes')),
                ('includes_en', models.TextField(blank=True, null=True, verbose_name='Package includes')),
                ('includes_uz', models.TextField(blank=True, null=True, verbose_name='Package includes')),
                ('includes_ru', models.TextField(blank=True, null=True, verbose_name='Package includes')),
                ('includes_it', models.TextField(blank=True, null=True, verbose_name='Package includes')),
                ('includes_es', models.TextField(blank=True, null=True, verbose_name='Package includes')),
                ('includes_ja', models.TextField(blank=True, null=True, verbose_name='Package includes')),
                ('min_participants', models.PositiveSmallIntegerField(default=10, verbose_name='Min participants')),
                ('max_participants', models.PositiveSmallIntegerField(default=500, verbose_name='Max participants')),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price per person (from)')),
                ('duration_days', models.PositiveSmallIntegerField(default=3, verbose_name='Duration (days)')),
                ('featured_destinations', models.ManyToManyField(blank=True, related_name='mice_packages', to='destinations.country', verbose_name='Featured destinations')),
            ],
            options={
                'verbose_name': 'Corporate package',
                'verbose_name_plural': 'Corporate packages',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
