# Generated by Django 5.2.15 on 2026-07-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticCity',
            fields=[
            ],
            options={
                'verbose_name': 'Domestic city',
                'verbose_name_plural': 'Domestic cities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('destinations.city',),
        ),
    ]
