"""Tests for the destinations app: Continent, Country, City, Attraction."""

import pytest
from django.urls import reverse

from apps.destinations.models import City
from tests import factories as f

pytestmark = pytest.mark.django_db


class TestContinent:
    def test_str(self):
        c = f.make_continent(name="Asia")
        assert str(c) == "Asia"

    def test_slug_autogenerated(self):
        c = f.make_continent(name="South America")
        assert c.slug == "south-america"

    def test_slug_preserved_when_given(self):
        c = f.make_continent(name="Europe", slug="custom-eu")
        assert c.slug == "custom-eu"

    def test_get_absolute_url(self):
        c = f.make_continent(name="Africa")
        assert c.get_absolute_url() == reverse("destinations:list") + "?continent=africa"


class TestCountry:
    def test_str_and_slug(self):
        country = f.make_country(name="Uzbekistan")
        assert str(country) == "Uzbekistan"
        assert country.slug == "uzbekistan"

    def test_get_absolute_url(self):
        country = f.make_country(name="Japan")
        assert country.get_absolute_url() == reverse(
            "destinations:country", kwargs={"slug": "japan"}
        )

    def test_tour_count_counts_only_active(self):
        country = f.make_country()
        active = f.make_tour(is_active=True)
        inactive = f.make_tour(is_active=False)
        active.destinations.add(country)
        inactive.destinations.add(country)
        assert country.tour_count == 1


class TestCity:
    def test_str_includes_country(self):
        country = f.make_country(name="Italy")
        city = f.make_city(name="Rome", country=country)
        assert str(city) == "Rome, Italy"

    def test_slug_autogenerated(self):
        city = f.make_city(name="New York")
        assert city.slug == "new-york"

    def test_get_absolute_url(self):
        country = f.make_country(name="France")
        city = f.make_city(name="Paris", country=country)
        assert city.get_absolute_url() == reverse(
            "destinations:city",
            kwargs={"country_slug": "france", "city_slug": "paris"},
        )

    def test_unique_together_country_slug(self):
        country = f.make_country()
        f.make_city(name="Springfield", country=country)
        with pytest.raises(Exception):
            City.objects.create(name="Springfield", country=country, slug="springfield")


class TestAttraction:
    def test_str_and_slug(self):
        a = f.make_attraction(name="Registan Square")
        assert str(a) == "Registan Square"
        assert a.slug == "registan-square"

    def test_default_category(self):
        a = f.make_attraction()
        assert a.category == "city"
