# Generated by Django 5.2.15 on 2026-07-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('phone', models.CharField(default='+998919917101', max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(default='burkhanov1c@gmail.com', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='Navoiy viloyati, Navoiy shahri, Jasorat 29-36', max_length=255, verbose_name='Address')),
                ('address_en', models.CharField(default='Navoiy viloyati, Navoiy shahri, Jasorat 29-36', max_length=255, null=True, verbose_name='Address')),
                ('address_uz', models.CharField(default='Navoiy viloyati, Navoiy shahri, Jasorat 29-36', max_length=255, null=True, verbose_name='Address')),
                ('address_ru', models.CharField(default='Navoiy viloyati, Navoiy shahri, Jasorat 29-36', max_length=255, null=True, verbose_name='Address')),
                ('address_it', models.CharField(default='Navoiy viloyati, Navoiy shahri, Jasorat 29-36', max_length=255, null=True, verbose_name='Address')),
                ('address_es', models.CharField(default='Navoiy viloyati, Navoiy shahri, Jasorat 29-36', max_length=255, null=True, verbose_name='Address')),
                ('address_ja', models.CharField(default='Navoiy viloyati, Navoiy shahri, Jasorat 29-36', max_length=255, null=True, verbose_name='Address')),
                ('working_hours', models.CharField(default='Dushanba–Shanba, 9:00–18:00', max_length=255, verbose_name='Working hours')),
                ('working_hours_en', models.CharField(default='Dushanba–Shanba, 9:00–18:00', max_length=255, null=True, verbose_name='Working hours')),
                ('working_hours_uz', models.CharField(default='Dushanba–Shanba, 9:00–18:00', max_length=255, null=True, verbose_name='Working hours')),
                ('working_hours_ru', models.CharField(default='Dushanba–Shanba, 9:00–18:00', max_length=255, null=True, verbose_name='Working hours')),
                ('working_hours_it', models.CharField(default='Dushanba–Shanba, 9:00–18:00', max_length=255, null=True, verbose_name='Working hours')),
                ('working_hours_es', models.CharField(default='Dushanba–Shanba, 9:00–18:00', max_length=255, null=True, verbose_name='Working hours')),
                ('working_hours_ja', models.CharField(default='Dushanba–Shanba, 9:00–18:00', max_length=255, null=True, verbose_name='Working hours')),
                ('youtube', models.URLField(blank=True, default='https://youtube.com/@Unituruz', verbose_name='YouTube')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/unitouruz', verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, default='https://t.me/unituruz', verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com/unituruz', verbose_name='Facebook')),
                ('latitude', models.FloatField(blank=True, default=40.0844, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, default=65.3792, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Contact Settings',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Display order')),
                ('page', models.CharField(choices=[('ichki_turlar', 'Domestic Tours'), ('home', 'Home'), ('tours', 'Tours'), ('destinations', 'Destinations'), ('hotels', 'Hotels'), ('guides', 'Guides')], db_index=True, default='ichki_turlar', help_text="Which page's hero slideshow this image belongs to.", max_length=32, verbose_name='Page')),
                ('image', models.ImageField(upload_to='hero_slides/', verbose_name='Image')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['page', 'order', '-created_at'],
            },
        ),
    ]
