# Generated by Django 5.2.15 on 2026-07-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Display order')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_uz', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_it', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_es', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_ja', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_en', models.TextField(null=True, verbose_name='Answer')),
                ('answer_uz', models.TextField(null=True, verbose_name='Answer')),
                ('answer_ru', models.TextField(null=True, verbose_name='Answer')),
                ('answer_it', models.TextField(null=True, verbose_name='Answer')),
                ('answer_es', models.TextField(null=True, verbose_name='Answer')),
                ('answer_ja', models.TextField(null=True, verbose_name='Answer')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
